// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvvfyielofnqvufoguqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dmZ5aWVsb2ZucXZ1Zm9ndXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTQzODQsImV4cCI6MjA4ODIzMDM4NH0.mDbwmiPS-Z9V8utu6UqkCPv2AvrB6tDv1RLYyxcm7rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});